### ISSUE TITLE
add `miscellaneous_plates` to configuration YAML

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/seqneut-pipeline#26]
The use case is if we have plates where we want to count barcodes (eg, for library pooling) but not fit curves or do any of the downstream steps done for `plates`.

The key should look like this:
```
miscellaneous_plates:

  <plate_name, eg "initial_pooling">
    date: <date>
    viral_library: <lib>
    neut_standard_set: <set>
    samples_csv: <filename>
```

The output would be in `./results/miscellaneous_plates/<plate_name>/<well>_<outfile.csv>` where `<outfile>` is `counts`, `invalid_counts`, or `fates`.

The `samples_csv` will have the following required columns and can also have other columns:
 - well
 - fastq
