### ISSUE TITLE
plate-level manual drops with 'wells' causes assertion error

### ISSUE THREAD

**Issue by ckikawa** [jbloomlab/seqneut-pipeline#45]
I have specified a `manual_drop` in my config for a specific plate, which looks like this:
 ```
plate17:
    group: SCH
    date: 2024-04-11
    viral_library: H3N2_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2024-04-11_neut_SCH_plate1.csv
    manual_drops:
      wells: 
        - [A9]
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
```

This causes an assertion error in the following block of code in the `process_plate17.ipynb` notebook. I'm not sure, but I believe this is because the `manual_drops` dictionary requires the key `wells` (plural!), but the actual column in the counts file is named `well` (singular!).
```
for filter_type, filter_drops in manual_drops.items():
    print(f"\nDropping {len(filter_drops)} {filter_type} specified in manual_drops")
    assert filter_type in qc_drops
    qc_drops[filter_type].update(
        {w: "manual_drop" for w in filter_drops if not isinstance(w, list)}
    )
    if filter_type == "barcode_wells":
        counts = counts[
            ~counts.assign(
                barcode_well=lambda x: x.apply(
                    lambda r: (r["barcode"], r["well"]), axis=1
                )
            )["barcode_well"].isin(qc_drops[filter_type])
        ]
    elif filter_type == "barcode_serum_replicates":
        counts = counts[
            ~counts.assign(
                barcode_serum_replicate=lambda x: x.apply(
                    lambda r: (r["barcode"], r["serum_replicate"]), axis=1
                )
            )["barcode_serum_replicate"].isin(qc_drops[filter_type])
        ]
    else:
        assert filter_type in set(counts.columns)
        counts = counts[~counts[filter_type].isin(qc_drops[filter_type])]
------------------

----- stdout -----

Dropping 1 wells specified in manual_drops
------------------

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[7], line 24
     16     counts = counts[
     17         ~counts.assign(
     18             barcode_serum_replicate=lambda x: x.apply(
   (...)
     21         )["barcode_serum_replicate"].isin(qc_drops[filter_type])
     22     ]
     23 else:
---> 24     assert filter_type in set(counts.columns)
     25     counts = counts[~counts[filter_type].isin(qc_drops[filter_type])]
```

In this case, this issue could be resolved by adding another `elif` statement to the same cell, something like:
```
    elif filter_type == "wells":
        counts = counts[
            ["well"].isin(qc_drops[filter_type])
        ]
```

Happy to try to tackle this @jbloom, unless you'd prefer to look at it!
